# Generated by Django 3.2.5 on 2021-07-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(max_length=11, unique=True, verbose_name='Tc Numarası')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyisim')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Telefon Numarası')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
